function [datasetResults] = get_computational_metrics_table(datasetResults, eegComputationalMetrics, subjectFileNames, sleepStatus, phaseOfStudy, subjectStatus, datasetType)

pac = false;
if pac
    numElectrodes = size(eegComputationalMetrics{1, 1}.electrodes, 2); 

    for i = 1:length(eegComputationalMetrics)
        if ~isempty(eegComputationalMetrics{i})

            dataLength = size(eegComputationalMetrics{i,1}.amplitude, 1);
            if dataLength ~= 0
                fileName = subjectFileNames{i}(1:end-4);
                patient_ID = Get_Patient_ID(fileName, datasetType);
                patient_ID   = repmat({patient_ID}, dataLength, 1);
                file_name    = repmat({fileName}, dataLength, 1);
                sleep_or_awake  = repmat({sleepStatus}, dataLength, 1);
                pre_or_post     = repmat({phaseOfStudy}, dataLength, 1);
                case_or_control = repmat({subjectStatus}, dataLength, 1);
                epoch_id = 1:dataLength;

                for j = 1:numElectrodes 
                    electrode = repmat(eegComputationalMetrics{i, 1}.electrodes(j), dataLength, 1); 

                    currentTable = table(patient_ID, file_name, sleep_or_awake, pre_or_post, case_or_control, electrode, ...
                        epoch_id', ...
                        eegComputationalMetrics{i, 1}.epochTimes(:,1), ...
                        eegComputationalMetrics{i, 1}.epochTimes(:,2), ...
                        eegComputationalMetrics{i, 1}.permEntDelta(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntDelta(:,j), ...
                        eegComputationalMetrics{i, 1}.permEntTheta(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntTheta(:,j), ...
                        eegComputationalMetrics{i, 1}.permEntAlpha(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntAlpha(:,j), ...
                        eegComputationalMetrics{i, 1}.permEntBeta(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntBeta(:,j), ...
                        eegComputationalMetrics{i, 1}.deltaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.thetaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.alphaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.betaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.broadPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.amplitude(:,j), ...
                        eegComputationalMetrics{i, 1}.SEF(:,j), ...
                        eegComputationalMetrics{i, 1}.MI(:,j), ...
                        eegComputationalMetrics{i, 1}.MVL(:,j), ...
                        'VariableNames', {'patient_ID', 'file_name', 'sleep_or_awake', 'pre_or_post', 'case_or_control', 'electrode_channel', ... % FIXED: electrod_channel -> electrode_channel
                        'epoch_id', 'epoch_start_index', 'epoch_stop_index', ... 
                        'permutation_entropy_delta', ...
                        'shannon_entropy_delta', ...
                        'permutation_entropy_theta', ...
                        'shannon_entropy_theta', ...
                        'permutation_entropy_alpha', ...
                        'shannon_entropy_alpha', ...
                        'permutation_entropy_beta', ...
                        'shannon_entropy_beta', ...
                        'power_spectral_density_delta', ...
                        'power_spectral_density_theta', ...
                        'power_spectral_density_alpha', ...
                        'power_spectral_density_beta', ...
                        'power_spectral_density_broadband', ...
                        'amplitude_range', ...
                        'spectral_edge_frequency', ...
                        'pac_mi', 'pac_mvl'});

                    datasetResults = [datasetResults; currentTable];
                end
            else
                continue;
            end
        else
            continue;
        end
    end

else
    numElectrodes = size(eegComputationalMetrics{1, 1}.electrodes, 2);

    for i = 1:length(eegComputationalMetrics)
        if ~isempty(eegComputationalMetrics{i})

            dataLength = size(eegComputationalMetrics{i,1}.amplitude, 1);
            if dataLength ~= 0

                fileName = subjectFileNames{i}(1:end-4);
                patient_ID = Get_Patient_ID(fileName, datasetType);
                patient_ID      = repmat({patient_ID}, dataLength, 1);
                file_name       = repmat({fileName}, dataLength, 1);
                sleep_or_awake  = repmat({sleepStatus}, dataLength, 1);
                pre_or_post     = repmat({phaseOfStudy}, dataLength, 1);
                case_or_control = repmat({subjectStatus}, dataLength, 1);
                epoch_id = 1:dataLength;

                for j = 1:numElectrodes % FIXED: typo numElectrods -> numElectrodes
                    electrode = repmat(eegComputationalMetrics{i, 1}.electrodes(j), dataLength, 1); % FIXED: {1,1} -> {i,1}, electrod -> electrode

                    currentTable = table(patient_ID, file_name, sleep_or_awake, pre_or_post, case_or_control, electrode, ...
                        epoch_id', ...
                        eegComputationalMetrics{i, 1}.epochTimes(:,1), ...
                        eegComputationalMetrics{i, 1}.epochTimes(:,2), ...
                        eegComputationalMetrics{i, 1}.permEntDelta(:,j), ... 
                        eegComputationalMetrics{i, 1}.shanEntDelta(:,j), ...  
                        eegComputationalMetrics{i, 1}.permEntTheta(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntTheta(:,j), ...
                        eegComputationalMetrics{i, 1}.permEntAlpha(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntAlpha(:,j), ...
                        eegComputationalMetrics{i, 1}.permEntBeta(:,j), ...
                        eegComputationalMetrics{i, 1}.shanEntBeta(:,j), ...
                        eegComputationalMetrics{i, 1}.deltaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.thetaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.alphaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.betaPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.broadPSD(:,j), ...
                        eegComputationalMetrics{i, 1}.amplitude(:,j), ...
                        eegComputationalMetrics{i, 1}.SEF(:,j), ...
                        'VariableNames', {'patient_ID', 'file_name', 'sleep_or_awake', 'pre_or_post', 'case_or_control', 'electrode_channel', ... % FIXED: electrod_channel -> electrode_channel
                        'epoch_id', 'epoch_start_index', 'epoch_stop_index', ... % FIXED: added missing commas
                        'permutation_entropy_delta', ...
                        'shannon_entropy_delta', ...
                        'permutation_entropy_theta', ...
                        'shannon_entropy_theta', ...
                        'permutation_entropy_alpha', ...
                        'shannon_entropy_alpha', ...
                        'permutation_entropy_beta', ...
                        'shannon_entropy_beta', ...
                        'power_spectral_density_delta', ...
                        'power_spectral_density_theta', ...
                        'power_spectral_density_alpha', ...
                        'power_spectral_density_beta', ...
                        'power_spectral_density_broadband', ...
                        'amplitude_range', ...
                        'spectral_edge_frequency'});

                    datasetResults = [datasetResults; currentTable];
                end
            else
                continue;
            end
        else
            continue;
        end
    end

end

end

%%

function PatientID = Get_Patient_ID(file_names, dataset)

if strcmp(dataset, 'NIMBIS')
    PatientID = file_names(1:7);

elseif strcmp(dataset, 'UCBshort')
    ucbID = file_names(1:3);
    patientNum = num2str(sscanf(ucbID, '%i'));
    numZeros = 3 - length(patientNum);
    myzeros = num2str(zeros(1, numZeros));
    myzeros = myzeros(~isspace(myzeros));
    PatientID = ['UCB' myzeros patientNum];

elseif strcmp(dataset, 'UCBlong')
    PatientID = 'Unknown'; % FIXED: typo 'Uknown' -> 'Unknown'

end

end